Repository ARMmbed/mbed-os-5-docs, pull requests merged in 2019-03, with the labels that each got.

#949 BLE build time configuration doc
  docs/reference/configuration/BLE.md
Labels: code dependency

#964 Add documentation on how to enable bare-metal
  docs/tutorials/migrate-from-mbed-os-2-to-5.md
Labels: code dependency

#983 crypto: Add Crypto API documentation
  docs/api/security/crypto.md
Labels: 5.12

#966 add initial version of PSA compliance test documents
  docs/porting/psa/testing_psa_service_compliance.md
Labels: 5.12

#1030 Document how to use tags and branches when importing projects
  docs/tools/CLI/cli-create.md
Labels: 5.12, wait to merge

#1032 Add Mbed CLI troubleshooting doc about python dependencies
  docs/tools/CLI/troubleshooting.md
Labels: 5.12
